;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        electric-newline-and-maybe-indent
        helm-ls-git-rebase-fixup
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        markdown-outdent-or-delete
        paredit-forward-delete
        paredit-forward-slurp-sexp
        ruby-end-space
        save-buffers-kill-terminal
        sgml-slash
        sh-assignment
        smex
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        forward-sexp
        ido-find-file
        mouse-save-then-kill
        mouse-set-region
        toggle-input-method
        yaml-electric-backspace
        ))
